author: "Rangle.io"
title: "Introduction to React"
subtitle: "Rangle.io"
copyrightyear: "2017"

# Code highlighting.
highlighter: rouge

# Magic to make URLs resolve both locally and on GitHub.
# See https://help.github.com/articles/repository-metadata-on-github-pages/.
repository: <USERNAME>/<PROJECT>

# Table of contents.
toc:
- title: Overview
  permalink: /overview/
  type: misc
- title: Getting Started
  permalink: /react-intro/
  type: lesson
  questions:
  - "What is React?"
  - "What problems does it solve?"
  - "What do I need to install to start using it?"
  - "How do I create a starter application?"
  keypoints:
  - "React is a declarative JavaScript view framework."
  - "React's development dependencies can be installed using NPM."
  - "Use `create-react-app` to generate a starter application."
- title: Making a Component
  permalink: /react-component/
  type: lesson
  questions:
  - "What is a React component?"
  - "How can I combine HTML and JavaScript to create a component?"
  - "How are HTML properties passed into components?"
  keypoints:
  - "A component is a function or class that transforms properties and state into a display."
  - "Use JSX to mix HTML and JavaScript."
  - "Use `{...}` to interpolate JavaScript expressions into HTML in JSX."
  - "Use modern 'fat arrow' notation to write functions."
  - "HTML properties are passed to components in a `props` object parameter."
  - "Use `className` instead of `class` in JSX."
- title: Introducing Robodex
  permalink: /react-outline/
  type: lesson
  questions:
  - "What are we going to build?"
  - "How do I display a single robot?"
  - "How do I display multiple robots?"
  - "How do I check that required properties are being provided?"
  keypoints:
  - "Every component must have a single root element."
  - "Use static data for early prototyping."
  - "Use the `prop-types` package and `classname.proptypes` to check properties."
  - Use JavaScript string interpolation with JSX expression interpolation."
- title: Creating a Card List
  permalink: /react-cardlist/
  type: lesson
- title: Creating the Container
  permalink: /react-container/
  type: lesson
- title: Lifecycle Methods
  permalink: /react-lifecycles/
  type: lesson
- title: React Summary
  permalink: /react-summary/
  type: lesson
- title: Introduction to Redux
  permalink: /redux-intro/
  type: lesson
- title: Actions and Reducers
  permalink: /redux-action-reducer/
  type: lesson
- title: Providing a Store
  permalink: /redux-store/
  type: lesson
- title: Making Connections
  permalink: /redux-connect/
  type: lesson
- title: Redux Logging
  permalink: /redux-logging/
  type: lesson
- title: Redux Thunk
  permalink: /redux-thunk/
  type: lesson
- title: Merging
  permalink: /redux-merge/
  type: lesson
- title: Advanced Topics
  permalink: /advanced/
  type: lesson
- permalink: /summary/
  title: Summary
  type: misc
- permalink: /guide/
  title: "Instructors' Guide"
  type: misc
- permalink: /gloss/
  title: Glossary
  type: misc
- permalink: /refs/
  title: References
  type: misc
- permalink: /license/
  title: License
  type: misc
- permalink: /conduct/
  title: Code of Conduct
  type: misc
- permalink: /contributing/
  title: Contributing
  type: misc
