author: "Rangle.io"
title: "Introduction to React"
subtitle: "Rangle.io"

# Code highlighting.
highlighter: rouge

# Magic to make URLs resolve both locally and on GitHub.
# See https://help.github.com/articles/repository-metadata-on-github-pages/.
repository: <USERNAME>/<PROJECT>

# Table of contents.
toc:
- title: Overview
  permalink: /overview/
  type: lesson
- title: Introduction to React
  permalink: /a0-react-intro/
  type: lesson
- title: Making a Component
  permalink: /a1-component/
  type: lesson
- title: Introducing Robodex
  permalink: /a2-outline/
  type: lesson
- title: Creating a Card List
  permalink: /a3-cardlist/
  type: lesson
- title: Creating the Container
  permalink: /a4-container/
  type: lesson
- title: Lifecycle Methods
  permalink: /a5-lifecycles/
  type: lesson
- title: React Summary
  permalink: /a6-react-summary/
  type: lesson
- title: Introduction to Redux
  permalink: /b0-redux-intro/
  type: lesson
- title: Installation
  permalink: /b1-install/
  type: lesson
- title: Actions and Reducers
  permalink: /b2-action-reducer/
  type: lesson
- title: Providing a Store
  permalink: /b3-store/
  type: lesson
- title: Making Connections
  permalink: /b4-connect/
  type: lesson
- title: Redux Logging
  permalink: /b5-logging/
  type: lesson
- title: Redux Thunk
  permalink: /b6-thunk/
  type: lesson
- title: Merging
  permalink: /b7-merge/
  type: lesson
- title: Advanced Topics
  permalink: /advanced/
  type: lesson
- permalink: /guide/
  title: Guide
  type: misc
- permalink: /gloss/
  title: Glossary
  type: misc
- permalink: /refs/
  title: References
  type: misc
- permalink: /license/
  title: License
  type: misc
- permalink: /conduct/
  title: Code of Conduct
  type: misc
- permalink: /contributing/
  title: Contributing
  type: misc
