author: "Rangle.io"
title: "Introduction to React"
subtitle: "Rangle.io"
copyrightyear: "2017"

# Code highlighting.
highlighter: rouge

# Magic to make URLs resolve both locally and on GitHub.
# See https://help.github.com/articles/repository-metadata-on-github-pages/.
repository: <USERNAME>/<PROJECT>

# Table of contents.
toc:
- title: Overview
  permalink: /overview/
  type: misc
- title: Getting Started
  permalink: /react-intro/
  type: lesson
  questions:
  - "What is React?"
  - "What problems does it solve?"
  - "What do I need to install to start using it?"
  - "How do I create a starter application?"
  keypoints:
  - "React is a declarative JavaScript view framework."
  - "React's development dependencies can be installed using NPM."
  - "Use `create-react-app` to generate a starter application."
- title: Making a Component
  permalink: /react-component/
  type: lesson
- title: Introducing Robodex
  permalink: /react-outline/
  type: lesson
- title: Creating a Card List
  permalink: /react-cardlist/
  type: lesson
- title: Creating the Container
  permalink: /react-container/
  type: lesson
- title: Lifecycle Methods
  permalink: /react-lifecycles/
  type: lesson
- title: React Summary
  permalink: /react-summary/
  type: lesson
- title: Introduction to Redux
  permalink: /redux-intro/
  type: lesson
- title: Actions and Reducers
  permalink: /redux-action-reducer/
  type: lesson
- title: Providing a Store
  permalink: /redux-store/
  type: lesson
- title: Making Connections
  permalink: /redux-connect/
  type: lesson
- title: Redux Logging
  permalink: /redux-logging/
  type: lesson
- title: Redux Thunk
  permalink: /redux-thunk/
  type: lesson
- title: Merging
  permalink: /redux-merge/
  type: lesson
- title: Advanced Topics
  permalink: /advanced/
  type: lesson
- permalink: /guide/
  title: Guide
  type: misc
- permalink: /gloss/
  title: Glossary
  type: misc
- permalink: /refs/
  title: References
  type: misc
- permalink: /license/
  title: License
  type: misc
- permalink: /conduct/
  title: Code of Conduct
  type: misc
- permalink: /contributing/
  title: Contributing
  type: misc
